version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
        update-types: ["security"]
    reviewers:
      - "ecanavesio"