version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    network_mode: host

  postgres:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: taxi24User
      POSTGRES_PASSWORD: SuperPowerfull24Pass
      POSTGRES_DB: taxi24
    volumes:
      - .database:/var/lib/postgresql/data

